<?php

declare(strict_types=1);

namespace App\Repository;

use App\Domain\ResetToken;
use PDO;

/**
 * @file PdoPasswordResetRepository.php
 * @brief PDO-based implementation of PasswordResetRepositoryInterface.
 *
 * @details Handles all database operations for password reset tokens stored
 *          in the password_reset_tokens table. Tokens expire after 30 minutes
 *          and can only be used once. Provides transaction control methods
 *          so the service layer can group multiple operations safely.
 *          No business logic is included here.
 */
class PdoPasswordResetRepository implements PasswordResetRepositoryInterface
{
    /**
     * @brief Creates a new PdoPasswordResetRepository with a PDO connection.
     *
     * @param PDO $pdo An active PDO database connection.
     */
    public function __construct(private readonly PDO $pdo)
    {
    }

    /**
     * @brief Starts a new database transaction.
     *
     * @details Calls PDO::beginTransaction(). Must be followed by commit()
     *          or rollBack() to end the transaction.
     *
     * @return void
     */
    public function beginTransaction(): void
    {
        $this->pdo->beginTransaction();
    }

    /**
     * @brief Commits the current database transaction.
     *
     * @details Calls PDO::commit() to save all changes made since the last
     *          beginTransaction() call.
     *
     * @return void
     */
    public function commit(): void
    {
        $this->pdo->commit();
    }

    /**
     * @brief Rolls back the current database transaction.
     *
     * @details Calls PDO::rollBack() to undo all changes made since the last
     *          beginTransaction() call. Called in the catch block on error.
     *
     * @return void
     */
    public function rollBack(): void
    {
        $this->pdo->rollBack();
    }

    /**
     * @brief Marks all unused reset tokens for a user as used.
     *
     * @details Sets used_at = NOW() for every row in password_reset_tokens
     *          where user_id matches and used_at IS NULL. This invalidates
     *          any old tokens before generating a new one.
     *
     * @param int $userId The ID of the user whose tokens should be revoked.
     *
     * @return void
     */
    public function revokeAllForUser(int $userId): void
    {
        $this->pdo->prepare(
            'UPDATE password_reset_tokens SET used_at = NOW() WHERE user_id = ? AND used_at IS NULL'
        )->execute([$userId]);
    }

    /**
     * @brief Inserts a new password reset token into the database.
     *
     * @details Creates a row in password_reset_tokens with the given user_id
     *          and token string. Sets expires_at to NOW() + INTERVAL 30 MINUTE.
     *          The used_at column starts as NULL, meaning the token is valid.
     *
     * @param int    $userId The ID of the user this token belongs to.
     * @param string $token  A 64-character hex token string generated by the caller.
     *
     * @return void
     */
    public function create(int $userId, string $token): void
    {
        $stmt = $this->pdo->prepare(
            'INSERT INTO password_reset_tokens (user_id, token, expires_at)
             VALUES (?, ?, NOW() + INTERVAL 30 MINUTE)'
        );
        $stmt->execute([$userId, $token]);
    }

    /**
     * @brief Finds a valid (not expired, not used) reset token by its string value.
     *
     * @details Queries password_reset_tokens for a row where the token string
     *          matches, expires_at is still in the future (expires_at > NOW()),
     *          and used_at IS NULL. Returns null if no valid token is found.
     *
     * @param string $token The token string entered by the user.
     *
     * @return ResetToken|null The matching ResetToken object, or null if invalid.
     */
    public function findValid(string $token): ?ResetToken
    {
        $stmt = $this->pdo->prepare(
            'SELECT token_id, user_id, token, expires_at, used_at
             FROM password_reset_tokens
             WHERE token = ?
               AND expires_at > NOW()
               AND used_at IS NULL
             LIMIT 1'
        );
        $stmt->execute([$token]);
        $row = $stmt->fetch();

        return $row ? ResetToken::fromRow($row) : null;
    }

    /**
     * @brief Marks a specific reset token as used by setting used_at to NOW().
     *
     * @details Updates the used_at column for the row with the given token_id.
     *          After this call, findValid() will no longer return this token.
     *
     * @param int $tokenId The ID of the token row to mark as used.
     *
     * @return void
     */
    public function markUsed(int $tokenId): void
    {
        $this->pdo->prepare(
            'UPDATE password_reset_tokens SET used_at = NOW() WHERE token_id = ?'
        )->execute([$tokenId]);
    }
}
