<?php

declare(strict_types=1);

namespace App\Repository;

use App\Domain\Session;
use PDO;

/**
 * @file PdoSessionRepository.php
 * @brief PDO-based implementation of SessionRepositoryInterface.
 *
 * @details Handles all database operations for user sessions stored in the
 *          user_sessions table. Sessions expire after 1 hour and can be
 *          revoked individually or all at once for a given user.
 *          No business logic is included here.
 */
class PdoSessionRepository implements SessionRepositoryInterface
{
    /**
     * @brief Creates a new PdoSessionRepository with a PDO connection.
     *
     * @param PDO $pdo An active PDO database connection.
     */
    public function __construct(private PDO $pdo)
    {
    }

    /**
     * @brief Inserts a new session row into the user_sessions table.
     *
     * @details Sets expires_at to NOW() + INTERVAL 1 HOUR. The session is
     *          valid until that time or until it is revoked with revoke().
     *          The token must be a unique random string generated by the caller.
     *
     * @param int    $userId    The ID of the user who is logging in.
     * @param string $token     A unique random token string for this session.
     * @param string $ip        The client IP address from the HTTP request.
     * @param string $userAgent The browser user agent string from the HTTP request.
     *
     * @return void
     */
    public function create(int $userId, string $token, string $ip, string $userAgent): void
    {
        $stmt = $this->pdo->prepare(
            'INSERT INTO user_sessions (user_id, token, ip_address, user_agent, expires_at)
             VALUES (?, ?, ?, ?, NOW() + INTERVAL 1 HOUR)'
        );
        $stmt->execute([$userId, $token, $ip, $userAgent]);
    }

    /**
     * @brief Extends the expiry of a session by 1 hour from the current time.
     *
     * @details Updates expires_at to NOW() + INTERVAL 1 HOUR for the row
     *          matching the token, but only if that session is not yet revoked
     *          (revoked_at IS NULL). This keeps an active session alive.
     *
     * @param string $token The session token to refresh.
     *
     * @return void
     */
    public function refresh(string $token): void
    {
        $stmt = $this->pdo->prepare(
            'UPDATE user_sessions SET expires_at = NOW() + INTERVAL 1 HOUR
             WHERE token = ? AND revoked_at IS NULL'
        );
        $stmt->execute([$token]);
    }

    /**
     * @brief Marks a single session as revoked by setting revoked_at to NOW().
     *
     * @details Once revoked_at is set, findActiveByToken() will no longer
     *          return this session. This is called on logout.
     *
     * @param string $token The session token to revoke.
     *
     * @return void
     */
    public function revoke(string $token): void
    {
        $stmt = $this->pdo->prepare(
            'UPDATE user_sessions SET revoked_at = NOW() WHERE token = ?'
        );
        $stmt->execute([$token]);
    }

    /**
     * @brief Revokes all active sessions for a given user.
     *
     * @details Updates every row in user_sessions that belongs to the given
     *          user_id and has revoked_at IS NULL. Sets revoked_at to NOW().
     *          Used after a password reset to force all devices to log out.
     *
     * @param int $userId The ID of the user whose sessions should be revoked.
     *
     * @return void
     */
    public function revokeAllForUser(int $userId): void
    {
        $stmt = $this->pdo->prepare(
            'UPDATE user_sessions SET revoked_at = NOW() WHERE user_id = ? AND revoked_at IS NULL'
        );
        $stmt->execute([$userId]);
    }

    /**
     * @brief Finds and returns an active session by its token string.
     *
     * @details Joins user_sessions with users and roles to include
     *          status_id, role_id, first_name, surname, and role_name.
     *          Only returns a result if the session is not revoked
     *          (revoked_at IS NULL) and has not yet expired (expires_at > NOW()).
     *          Returns null if no such session exists.
     *
     * @param string $token The session token to look up.
     *
     * @return Session|null The active Session object, or null if not found.
     */
    public function findActiveByToken(string $token): ?Session
    {
        $stmt = $this->pdo->prepare(
            'SELECT s.session_id, s.user_id, s.token, s.ip_address, s.user_agent,
                    s.expires_at, s.revoked_at,
                    u.status_id, u.role_id, u.first_name, u.surname, r.role_name
             FROM user_sessions s
             JOIN users u ON u.user_id = s.user_id
             JOIN roles r ON r.role_id = u.role_id
             WHERE s.token = ?
               AND s.revoked_at IS NULL
               AND s.expires_at > NOW()
             LIMIT 1'
        );
        $stmt->execute([$token]);
        $row = $stmt->fetch();

        return $row ? Session::fromRow($row) : null;
    }
}
